/**
 * @fileoverview gRPC-Web generated client stub for business.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.32.1
// source: api/proto/business/v1/claim_request.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')

var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js')
const proto = {};
proto.business = {};
proto.business.v1 = require('./claim_request_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.business.v1.ClaimRequestServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.business.v1.ClaimRequestServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.business.v1.CreateClaimRequestRequest,
 *   !proto.business.v1.CreateClaimRequestResponse>}
 */
const methodDescriptor_ClaimRequestService_CreateClaimRequest = new grpc.web.MethodDescriptor(
  '/business.v1.ClaimRequestService/CreateClaimRequest',
  grpc.web.MethodType.UNARY,
  proto.business.v1.CreateClaimRequestRequest,
  proto.business.v1.CreateClaimRequestResponse,
  /**
   * @param {!proto.business.v1.CreateClaimRequestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.business.v1.CreateClaimRequestResponse.deserializeBinary
);


/**
 * @param {!proto.business.v1.CreateClaimRequestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.business.v1.CreateClaimRequestResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.business.v1.CreateClaimRequestResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.business.v1.ClaimRequestServiceClient.prototype.createClaimRequest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/business.v1.ClaimRequestService/CreateClaimRequest',
      request,
      metadata || {},
      methodDescriptor_ClaimRequestService_CreateClaimRequest,
      callback);
};


/**
 * @param {!proto.business.v1.CreateClaimRequestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.business.v1.CreateClaimRequestResponse>}
 *     Promise that resolves to the response
 */
proto.business.v1.ClaimRequestServicePromiseClient.prototype.createClaimRequest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/business.v1.ClaimRequestService/CreateClaimRequest',
      request,
      metadata || {},
      methodDescriptor_ClaimRequestService_CreateClaimRequest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.business.v1.GetClaimRequestRequest,
 *   !proto.business.v1.GetClaimRequestResponse>}
 */
const methodDescriptor_ClaimRequestService_GetClaimRequest = new grpc.web.MethodDescriptor(
  '/business.v1.ClaimRequestService/GetClaimRequest',
  grpc.web.MethodType.UNARY,
  proto.business.v1.GetClaimRequestRequest,
  proto.business.v1.GetClaimRequestResponse,
  /**
   * @param {!proto.business.v1.GetClaimRequestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.business.v1.GetClaimRequestResponse.deserializeBinary
);


/**
 * @param {!proto.business.v1.GetClaimRequestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.business.v1.GetClaimRequestResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.business.v1.GetClaimRequestResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.business.v1.ClaimRequestServiceClient.prototype.getClaimRequest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/business.v1.ClaimRequestService/GetClaimRequest',
      request,
      metadata || {},
      methodDescriptor_ClaimRequestService_GetClaimRequest,
      callback);
};


/**
 * @param {!proto.business.v1.GetClaimRequestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.business.v1.GetClaimRequestResponse>}
 *     Promise that resolves to the response
 */
proto.business.v1.ClaimRequestServicePromiseClient.prototype.getClaimRequest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/business.v1.ClaimRequestService/GetClaimRequest',
      request,
      metadata || {},
      methodDescriptor_ClaimRequestService_GetClaimRequest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.business.v1.ListClaimRequestsRequest,
 *   !proto.business.v1.ListClaimRequestsResponse>}
 */
const methodDescriptor_ClaimRequestService_ListClaimRequests = new grpc.web.MethodDescriptor(
  '/business.v1.ClaimRequestService/ListClaimRequests',
  grpc.web.MethodType.UNARY,
  proto.business.v1.ListClaimRequestsRequest,
  proto.business.v1.ListClaimRequestsResponse,
  /**
   * @param {!proto.business.v1.ListClaimRequestsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.business.v1.ListClaimRequestsResponse.deserializeBinary
);


/**
 * @param {!proto.business.v1.ListClaimRequestsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.business.v1.ListClaimRequestsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.business.v1.ListClaimRequestsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.business.v1.ClaimRequestServiceClient.prototype.listClaimRequests =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/business.v1.ClaimRequestService/ListClaimRequests',
      request,
      metadata || {},
      methodDescriptor_ClaimRequestService_ListClaimRequests,
      callback);
};


/**
 * @param {!proto.business.v1.ListClaimRequestsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.business.v1.ListClaimRequestsResponse>}
 *     Promise that resolves to the response
 */
proto.business.v1.ClaimRequestServicePromiseClient.prototype.listClaimRequests =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/business.v1.ClaimRequestService/ListClaimRequests',
      request,
      metadata || {},
      methodDescriptor_ClaimRequestService_ListClaimRequests);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.business.v1.ApproveClaimRequestRequest,
 *   !proto.business.v1.ApproveClaimRequestResponse>}
 */
const methodDescriptor_ClaimRequestService_ApproveClaimRequest = new grpc.web.MethodDescriptor(
  '/business.v1.ClaimRequestService/ApproveClaimRequest',
  grpc.web.MethodType.UNARY,
  proto.business.v1.ApproveClaimRequestRequest,
  proto.business.v1.ApproveClaimRequestResponse,
  /**
   * @param {!proto.business.v1.ApproveClaimRequestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.business.v1.ApproveClaimRequestResponse.deserializeBinary
);


/**
 * @param {!proto.business.v1.ApproveClaimRequestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.business.v1.ApproveClaimRequestResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.business.v1.ApproveClaimRequestResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.business.v1.ClaimRequestServiceClient.prototype.approveClaimRequest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/business.v1.ClaimRequestService/ApproveClaimRequest',
      request,
      metadata || {},
      methodDescriptor_ClaimRequestService_ApproveClaimRequest,
      callback);
};


/**
 * @param {!proto.business.v1.ApproveClaimRequestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.business.v1.ApproveClaimRequestResponse>}
 *     Promise that resolves to the response
 */
proto.business.v1.ClaimRequestServicePromiseClient.prototype.approveClaimRequest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/business.v1.ClaimRequestService/ApproveClaimRequest',
      request,
      metadata || {},
      methodDescriptor_ClaimRequestService_ApproveClaimRequest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.business.v1.RejectClaimRequestRequest,
 *   !proto.business.v1.RejectClaimRequestResponse>}
 */
const methodDescriptor_ClaimRequestService_RejectClaimRequest = new grpc.web.MethodDescriptor(
  '/business.v1.ClaimRequestService/RejectClaimRequest',
  grpc.web.MethodType.UNARY,
  proto.business.v1.RejectClaimRequestRequest,
  proto.business.v1.RejectClaimRequestResponse,
  /**
   * @param {!proto.business.v1.RejectClaimRequestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.business.v1.RejectClaimRequestResponse.deserializeBinary
);


/**
 * @param {!proto.business.v1.RejectClaimRequestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.business.v1.RejectClaimRequestResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.business.v1.RejectClaimRequestResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.business.v1.ClaimRequestServiceClient.prototype.rejectClaimRequest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/business.v1.ClaimRequestService/RejectClaimRequest',
      request,
      metadata || {},
      methodDescriptor_ClaimRequestService_RejectClaimRequest,
      callback);
};


/**
 * @param {!proto.business.v1.RejectClaimRequestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.business.v1.RejectClaimRequestResponse>}
 *     Promise that resolves to the response
 */
proto.business.v1.ClaimRequestServicePromiseClient.prototype.rejectClaimRequest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/business.v1.ClaimRequestService/RejectClaimRequest',
      request,
      metadata || {},
      methodDescriptor_ClaimRequestService_RejectClaimRequest);
};


module.exports = proto.business.v1;

