/**
 * @fileoverview gRPC-Web generated client stub for lviv.auth.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.32.1
// source: auth/v1/auth.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"
import * as auth_v1_auth_pb from './auth_pb'; // proto import: "auth/v1/auth.proto"


export class AuthServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRegister = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/Register',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.RegisterRequest,
    auth_v1_auth_pb.RegisterResponse,
    (request: auth_v1_auth_pb.RegisterRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.RegisterResponse.deserializeBinary
  );

  register(
    request: auth_v1_auth_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.RegisterResponse>;

  register(
    request: auth_v1_auth_pb.RegisterRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.RegisterResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.RegisterResponse>;

  register(
    request: auth_v1_auth_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.RegisterResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/Register',
        request,
        metadata || {},
        this.methodDescriptorRegister,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/Register',
    request,
    metadata || {},
    this.methodDescriptorRegister);
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/Login',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.LoginRequest,
    auth_v1_auth_pb.LoginResponse,
    (request: auth_v1_auth_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.LoginResponse.deserializeBinary
  );

  login(
    request: auth_v1_auth_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.LoginResponse>;

  login(
    request: auth_v1_auth_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.LoginResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.LoginResponse>;

  login(
    request: auth_v1_auth_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.LoginResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

  methodDescriptorLogout = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/Logout',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.LogoutRequest,
    auth_v1_auth_pb.LogoutResponse,
    (request: auth_v1_auth_pb.LogoutRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.LogoutResponse.deserializeBinary
  );

  logout(
    request: auth_v1_auth_pb.LogoutRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.LogoutResponse>;

  logout(
    request: auth_v1_auth_pb.LogoutRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.LogoutResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.LogoutResponse>;

  logout(
    request: auth_v1_auth_pb.LogoutRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.LogoutResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/Logout',
        request,
        metadata || {},
        this.methodDescriptorLogout,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/Logout',
    request,
    metadata || {},
    this.methodDescriptorLogout);
  }

  methodDescriptorRefreshToken = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/RefreshToken',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.RefreshTokenRequest,
    auth_v1_auth_pb.RefreshTokenResponse,
    (request: auth_v1_auth_pb.RefreshTokenRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.RefreshTokenResponse.deserializeBinary
  );

  refreshToken(
    request: auth_v1_auth_pb.RefreshTokenRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.RefreshTokenResponse>;

  refreshToken(
    request: auth_v1_auth_pb.RefreshTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.RefreshTokenResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.RefreshTokenResponse>;

  refreshToken(
    request: auth_v1_auth_pb.RefreshTokenRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.RefreshTokenResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/RefreshToken',
        request,
        metadata || {},
        this.methodDescriptorRefreshToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/RefreshToken',
    request,
    metadata || {},
    this.methodDescriptorRefreshToken);
  }

  methodDescriptorValidateToken = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/ValidateToken',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.ValidateTokenRequest,
    auth_v1_auth_pb.ValidateTokenResponse,
    (request: auth_v1_auth_pb.ValidateTokenRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.ValidateTokenResponse.deserializeBinary
  );

  validateToken(
    request: auth_v1_auth_pb.ValidateTokenRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.ValidateTokenResponse>;

  validateToken(
    request: auth_v1_auth_pb.ValidateTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.ValidateTokenResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.ValidateTokenResponse>;

  validateToken(
    request: auth_v1_auth_pb.ValidateTokenRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.ValidateTokenResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/ValidateToken',
        request,
        metadata || {},
        this.methodDescriptorValidateToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/ValidateToken',
    request,
    metadata || {},
    this.methodDescriptorValidateToken);
  }

  methodDescriptorVerifyEmail = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/VerifyEmail',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.VerifyEmailRequest,
    auth_v1_auth_pb.VerifyEmailResponse,
    (request: auth_v1_auth_pb.VerifyEmailRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.VerifyEmailResponse.deserializeBinary
  );

  verifyEmail(
    request: auth_v1_auth_pb.VerifyEmailRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.VerifyEmailResponse>;

  verifyEmail(
    request: auth_v1_auth_pb.VerifyEmailRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.VerifyEmailResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.VerifyEmailResponse>;

  verifyEmail(
    request: auth_v1_auth_pb.VerifyEmailRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.VerifyEmailResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/VerifyEmail',
        request,
        metadata || {},
        this.methodDescriptorVerifyEmail,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/VerifyEmail',
    request,
    metadata || {},
    this.methodDescriptorVerifyEmail);
  }

  methodDescriptorResendVerificationEmail = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/ResendVerificationEmail',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.ResendVerificationEmailRequest,
    auth_v1_auth_pb.ResendVerificationEmailResponse,
    (request: auth_v1_auth_pb.ResendVerificationEmailRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.ResendVerificationEmailResponse.deserializeBinary
  );

  resendVerificationEmail(
    request: auth_v1_auth_pb.ResendVerificationEmailRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.ResendVerificationEmailResponse>;

  resendVerificationEmail(
    request: auth_v1_auth_pb.ResendVerificationEmailRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.ResendVerificationEmailResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.ResendVerificationEmailResponse>;

  resendVerificationEmail(
    request: auth_v1_auth_pb.ResendVerificationEmailRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.ResendVerificationEmailResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/ResendVerificationEmail',
        request,
        metadata || {},
        this.methodDescriptorResendVerificationEmail,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/ResendVerificationEmail',
    request,
    metadata || {},
    this.methodDescriptorResendVerificationEmail);
  }

  methodDescriptorGetProfile = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/GetProfile',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.GetProfileRequest,
    auth_v1_auth_pb.GetProfileResponse,
    (request: auth_v1_auth_pb.GetProfileRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.GetProfileResponse.deserializeBinary
  );

  getProfile(
    request: auth_v1_auth_pb.GetProfileRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.GetProfileResponse>;

  getProfile(
    request: auth_v1_auth_pb.GetProfileRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.GetProfileResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.GetProfileResponse>;

  getProfile(
    request: auth_v1_auth_pb.GetProfileRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.GetProfileResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/GetProfile',
        request,
        metadata || {},
        this.methodDescriptorGetProfile,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/GetProfile',
    request,
    metadata || {},
    this.methodDescriptorGetProfile);
  }

  methodDescriptorUpdateProfile = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/UpdateProfile',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.UpdateProfileRequest,
    auth_v1_auth_pb.UpdateProfileResponse,
    (request: auth_v1_auth_pb.UpdateProfileRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.UpdateProfileResponse.deserializeBinary
  );

  updateProfile(
    request: auth_v1_auth_pb.UpdateProfileRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.UpdateProfileResponse>;

  updateProfile(
    request: auth_v1_auth_pb.UpdateProfileRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.UpdateProfileResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.UpdateProfileResponse>;

  updateProfile(
    request: auth_v1_auth_pb.UpdateProfileRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.UpdateProfileResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/UpdateProfile',
        request,
        metadata || {},
        this.methodDescriptorUpdateProfile,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/UpdateProfile',
    request,
    metadata || {},
    this.methodDescriptorUpdateProfile);
  }

  methodDescriptorEnableMFA = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/EnableMFA',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.EnableMFARequest,
    auth_v1_auth_pb.EnableMFAResponse,
    (request: auth_v1_auth_pb.EnableMFARequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.EnableMFAResponse.deserializeBinary
  );

  enableMFA(
    request: auth_v1_auth_pb.EnableMFARequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.EnableMFAResponse>;

  enableMFA(
    request: auth_v1_auth_pb.EnableMFARequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.EnableMFAResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.EnableMFAResponse>;

  enableMFA(
    request: auth_v1_auth_pb.EnableMFARequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.EnableMFAResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/EnableMFA',
        request,
        metadata || {},
        this.methodDescriptorEnableMFA,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/EnableMFA',
    request,
    metadata || {},
    this.methodDescriptorEnableMFA);
  }

  methodDescriptorVerifyMFA = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/VerifyMFA',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.VerifyMFARequest,
    auth_v1_auth_pb.VerifyMFAResponse,
    (request: auth_v1_auth_pb.VerifyMFARequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.VerifyMFAResponse.deserializeBinary
  );

  verifyMFA(
    request: auth_v1_auth_pb.VerifyMFARequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.VerifyMFAResponse>;

  verifyMFA(
    request: auth_v1_auth_pb.VerifyMFARequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.VerifyMFAResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.VerifyMFAResponse>;

  verifyMFA(
    request: auth_v1_auth_pb.VerifyMFARequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.VerifyMFAResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/VerifyMFA',
        request,
        metadata || {},
        this.methodDescriptorVerifyMFA,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/VerifyMFA',
    request,
    metadata || {},
    this.methodDescriptorVerifyMFA);
  }

  methodDescriptorDisableMFA = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/DisableMFA',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.DisableMFARequest,
    google_protobuf_empty_pb.Empty,
    (request: auth_v1_auth_pb.DisableMFARequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  disableMFA(
    request: auth_v1_auth_pb.DisableMFARequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  disableMFA(
    request: auth_v1_auth_pb.DisableMFARequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  disableMFA(
    request: auth_v1_auth_pb.DisableMFARequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/DisableMFA',
        request,
        metadata || {},
        this.methodDescriptorDisableMFA,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/DisableMFA',
    request,
    metadata || {},
    this.methodDescriptorDisableMFA);
  }

  methodDescriptorChangePassword = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/ChangePassword',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.ChangePasswordRequest,
    auth_v1_auth_pb.ChangePasswordResponse,
    (request: auth_v1_auth_pb.ChangePasswordRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.ChangePasswordResponse.deserializeBinary
  );

  changePassword(
    request: auth_v1_auth_pb.ChangePasswordRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.ChangePasswordResponse>;

  changePassword(
    request: auth_v1_auth_pb.ChangePasswordRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.ChangePasswordResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.ChangePasswordResponse>;

  changePassword(
    request: auth_v1_auth_pb.ChangePasswordRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.ChangePasswordResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/ChangePassword',
        request,
        metadata || {},
        this.methodDescriptorChangePassword,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/ChangePassword',
    request,
    metadata || {},
    this.methodDescriptorChangePassword);
  }

  methodDescriptorRequestPasswordReset = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/RequestPasswordReset',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.PasswordResetRequest,
    auth_v1_auth_pb.PasswordResetResponse,
    (request: auth_v1_auth_pb.PasswordResetRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.PasswordResetResponse.deserializeBinary
  );

  requestPasswordReset(
    request: auth_v1_auth_pb.PasswordResetRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.PasswordResetResponse>;

  requestPasswordReset(
    request: auth_v1_auth_pb.PasswordResetRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.PasswordResetResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.PasswordResetResponse>;

  requestPasswordReset(
    request: auth_v1_auth_pb.PasswordResetRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.PasswordResetResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/RequestPasswordReset',
        request,
        metadata || {},
        this.methodDescriptorRequestPasswordReset,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/RequestPasswordReset',
    request,
    metadata || {},
    this.methodDescriptorRequestPasswordReset);
  }

  methodDescriptorValidateResetToken = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/ValidateResetToken',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.ValidateResetTokenRequest,
    auth_v1_auth_pb.ValidateResetTokenResponse,
    (request: auth_v1_auth_pb.ValidateResetTokenRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.ValidateResetTokenResponse.deserializeBinary
  );

  validateResetToken(
    request: auth_v1_auth_pb.ValidateResetTokenRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.ValidateResetTokenResponse>;

  validateResetToken(
    request: auth_v1_auth_pb.ValidateResetTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.ValidateResetTokenResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.ValidateResetTokenResponse>;

  validateResetToken(
    request: auth_v1_auth_pb.ValidateResetTokenRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.ValidateResetTokenResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/ValidateResetToken',
        request,
        metadata || {},
        this.methodDescriptorValidateResetToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/ValidateResetToken',
    request,
    metadata || {},
    this.methodDescriptorValidateResetToken);
  }

  methodDescriptorConfirmPasswordReset = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/ConfirmPasswordReset',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.ConfirmPasswordResetRequest,
    auth_v1_auth_pb.ConfirmPasswordResetResponse,
    (request: auth_v1_auth_pb.ConfirmPasswordResetRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.ConfirmPasswordResetResponse.deserializeBinary
  );

  confirmPasswordReset(
    request: auth_v1_auth_pb.ConfirmPasswordResetRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.ConfirmPasswordResetResponse>;

  confirmPasswordReset(
    request: auth_v1_auth_pb.ConfirmPasswordResetRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.ConfirmPasswordResetResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.ConfirmPasswordResetResponse>;

  confirmPasswordReset(
    request: auth_v1_auth_pb.ConfirmPasswordResetRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.ConfirmPasswordResetResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/ConfirmPasswordReset',
        request,
        metadata || {},
        this.methodDescriptorConfirmPasswordReset,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/ConfirmPasswordReset',
    request,
    metadata || {},
    this.methodDescriptorConfirmPasswordReset);
  }

  methodDescriptorGetDevVerificationToken = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/GetDevVerificationToken',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.GetDevVerificationTokenRequest,
    auth_v1_auth_pb.GetDevVerificationTokenResponse,
    (request: auth_v1_auth_pb.GetDevVerificationTokenRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.GetDevVerificationTokenResponse.deserializeBinary
  );

  getDevVerificationToken(
    request: auth_v1_auth_pb.GetDevVerificationTokenRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.GetDevVerificationTokenResponse>;

  getDevVerificationToken(
    request: auth_v1_auth_pb.GetDevVerificationTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.GetDevVerificationTokenResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.GetDevVerificationTokenResponse>;

  getDevVerificationToken(
    request: auth_v1_auth_pb.GetDevVerificationTokenRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.GetDevVerificationTokenResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/GetDevVerificationToken',
        request,
        metadata || {},
        this.methodDescriptorGetDevVerificationToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/GetDevVerificationToken',
    request,
    metadata || {},
    this.methodDescriptorGetDevVerificationToken);
  }

  methodDescriptorInitiatePhoneAuth = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/InitiatePhoneAuth',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.InitiatePhoneAuthRequest,
    auth_v1_auth_pb.InitiatePhoneAuthResponse,
    (request: auth_v1_auth_pb.InitiatePhoneAuthRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.InitiatePhoneAuthResponse.deserializeBinary
  );

  initiatePhoneAuth(
    request: auth_v1_auth_pb.InitiatePhoneAuthRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.InitiatePhoneAuthResponse>;

  initiatePhoneAuth(
    request: auth_v1_auth_pb.InitiatePhoneAuthRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.InitiatePhoneAuthResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.InitiatePhoneAuthResponse>;

  initiatePhoneAuth(
    request: auth_v1_auth_pb.InitiatePhoneAuthRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.InitiatePhoneAuthResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/InitiatePhoneAuth',
        request,
        metadata || {},
        this.methodDescriptorInitiatePhoneAuth,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/InitiatePhoneAuth',
    request,
    metadata || {},
    this.methodDescriptorInitiatePhoneAuth);
  }

  methodDescriptorVerifyPhoneAuth = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/VerifyPhoneAuth',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.VerifyPhoneAuthRequest,
    auth_v1_auth_pb.VerifyPhoneAuthResponse,
    (request: auth_v1_auth_pb.VerifyPhoneAuthRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.VerifyPhoneAuthResponse.deserializeBinary
  );

  verifyPhoneAuth(
    request: auth_v1_auth_pb.VerifyPhoneAuthRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.VerifyPhoneAuthResponse>;

  verifyPhoneAuth(
    request: auth_v1_auth_pb.VerifyPhoneAuthRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.VerifyPhoneAuthResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.VerifyPhoneAuthResponse>;

  verifyPhoneAuth(
    request: auth_v1_auth_pb.VerifyPhoneAuthRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.VerifyPhoneAuthResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/VerifyPhoneAuth',
        request,
        metadata || {},
        this.methodDescriptorVerifyPhoneAuth,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/VerifyPhoneAuth',
    request,
    metadata || {},
    this.methodDescriptorVerifyPhoneAuth);
  }

  methodDescriptorInitiateWhatsAppAuth = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/InitiateWhatsAppAuth',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.InitiateWhatsAppAuthRequest,
    auth_v1_auth_pb.InitiateWhatsAppAuthResponse,
    (request: auth_v1_auth_pb.InitiateWhatsAppAuthRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.InitiateWhatsAppAuthResponse.deserializeBinary
  );

  initiateWhatsAppAuth(
    request: auth_v1_auth_pb.InitiateWhatsAppAuthRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.InitiateWhatsAppAuthResponse>;

  initiateWhatsAppAuth(
    request: auth_v1_auth_pb.InitiateWhatsAppAuthRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.InitiateWhatsAppAuthResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.InitiateWhatsAppAuthResponse>;

  initiateWhatsAppAuth(
    request: auth_v1_auth_pb.InitiateWhatsAppAuthRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.InitiateWhatsAppAuthResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/InitiateWhatsAppAuth',
        request,
        metadata || {},
        this.methodDescriptorInitiateWhatsAppAuth,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/InitiateWhatsAppAuth',
    request,
    metadata || {},
    this.methodDescriptorInitiateWhatsAppAuth);
  }

  methodDescriptorVerifyWhatsAppAuth = new grpcWeb.MethodDescriptor(
    '/lviv.auth.v1.AuthService/VerifyWhatsAppAuth',
    grpcWeb.MethodType.UNARY,
    auth_v1_auth_pb.VerifyWhatsAppAuthRequest,
    auth_v1_auth_pb.VerifyWhatsAppAuthResponse,
    (request: auth_v1_auth_pb.VerifyWhatsAppAuthRequest) => {
      return request.serializeBinary();
    },
    auth_v1_auth_pb.VerifyWhatsAppAuthResponse.deserializeBinary
  );

  verifyWhatsAppAuth(
    request: auth_v1_auth_pb.VerifyWhatsAppAuthRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_v1_auth_pb.VerifyWhatsAppAuthResponse>;

  verifyWhatsAppAuth(
    request: auth_v1_auth_pb.VerifyWhatsAppAuthRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.VerifyWhatsAppAuthResponse) => void): grpcWeb.ClientReadableStream<auth_v1_auth_pb.VerifyWhatsAppAuthResponse>;

  verifyWhatsAppAuth(
    request: auth_v1_auth_pb.VerifyWhatsAppAuthRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_v1_auth_pb.VerifyWhatsAppAuthResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lviv.auth.v1.AuthService/VerifyWhatsAppAuth',
        request,
        metadata || {},
        this.methodDescriptorVerifyWhatsAppAuth,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lviv.auth.v1.AuthService/VerifyWhatsAppAuth',
    request,
    metadata || {},
    this.methodDescriptorVerifyWhatsAppAuth);
  }

}

