/**
 * @fileoverview gRPC-Web generated client stub for business.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.30.2
// source: business/v1/business.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as business_v1_business_pb from '../../business/v1/business_pb'; // proto import: "business/v1/business.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"


export class BusinessServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateBusiness = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/CreateBusiness',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.CreateBusinessRequest,
    business_v1_business_pb.CreateBusinessResponse,
    (request: business_v1_business_pb.CreateBusinessRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.CreateBusinessResponse.deserializeBinary
  );

  createBusiness(
    request: business_v1_business_pb.CreateBusinessRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.CreateBusinessResponse>;

  createBusiness(
    request: business_v1_business_pb.CreateBusinessRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.CreateBusinessResponse>;

  createBusiness(
    request: business_v1_business_pb.CreateBusinessRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/CreateBusiness',
        request,
        metadata || {},
        this.methodDescriptorCreateBusiness,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/CreateBusiness',
    request,
    metadata || {},
    this.methodDescriptorCreateBusiness);
  }

  methodDescriptorGetBusiness = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/GetBusiness',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.GetBusinessRequest,
    business_v1_business_pb.GetBusinessResponse,
    (request: business_v1_business_pb.GetBusinessRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.GetBusinessResponse.deserializeBinary
  );

  getBusiness(
    request: business_v1_business_pb.GetBusinessRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.GetBusinessResponse>;

  getBusiness(
    request: business_v1_business_pb.GetBusinessRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.GetBusinessResponse>;

  getBusiness(
    request: business_v1_business_pb.GetBusinessRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/GetBusiness',
        request,
        metadata || {},
        this.methodDescriptorGetBusiness,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/GetBusiness',
    request,
    metadata || {},
    this.methodDescriptorGetBusiness);
  }

  methodDescriptorGetBusinessByName = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/GetBusinessByName',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.GetBusinessByNameRequest,
    business_v1_business_pb.GetBusinessByNameResponse,
    (request: business_v1_business_pb.GetBusinessByNameRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.GetBusinessByNameResponse.deserializeBinary
  );

  getBusinessByName(
    request: business_v1_business_pb.GetBusinessByNameRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.GetBusinessByNameResponse>;

  getBusinessByName(
    request: business_v1_business_pb.GetBusinessByNameRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessByNameResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.GetBusinessByNameResponse>;

  getBusinessByName(
    request: business_v1_business_pb.GetBusinessByNameRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessByNameResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/GetBusinessByName',
        request,
        metadata || {},
        this.methodDescriptorGetBusinessByName,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/GetBusinessByName',
    request,
    metadata || {},
    this.methodDescriptorGetBusinessByName);
  }

  methodDescriptorUpdateBusiness = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/UpdateBusiness',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.UpdateBusinessRequest,
    business_v1_business_pb.UpdateBusinessResponse,
    (request: business_v1_business_pb.UpdateBusinessRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.UpdateBusinessResponse.deserializeBinary
  );

  updateBusiness(
    request: business_v1_business_pb.UpdateBusinessRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.UpdateBusinessResponse>;

  updateBusiness(
    request: business_v1_business_pb.UpdateBusinessRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.UpdateBusinessResponse>;

  updateBusiness(
    request: business_v1_business_pb.UpdateBusinessRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/UpdateBusiness',
        request,
        metadata || {},
        this.methodDescriptorUpdateBusiness,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/UpdateBusiness',
    request,
    metadata || {},
    this.methodDescriptorUpdateBusiness);
  }

  methodDescriptorDeleteBusiness = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/DeleteBusiness',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.DeleteBusinessRequest,
    google_protobuf_empty_pb.Empty,
    (request: business_v1_business_pb.DeleteBusinessRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteBusiness(
    request: business_v1_business_pb.DeleteBusinessRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteBusiness(
    request: business_v1_business_pb.DeleteBusinessRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteBusiness(
    request: business_v1_business_pb.DeleteBusinessRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/DeleteBusiness',
        request,
        metadata || {},
        this.methodDescriptorDeleteBusiness,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/DeleteBusiness',
    request,
    metadata || {},
    this.methodDescriptorDeleteBusiness);
  }

  methodDescriptorListBusinesses = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/ListBusinesses',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.ListBusinessesRequest,
    business_v1_business_pb.ListBusinessesResponse,
    (request: business_v1_business_pb.ListBusinessesRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.ListBusinessesResponse.deserializeBinary
  );

  listBusinesses(
    request: business_v1_business_pb.ListBusinessesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.ListBusinessesResponse>;

  listBusinesses(
    request: business_v1_business_pb.ListBusinessesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBusinessesResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.ListBusinessesResponse>;

  listBusinesses(
    request: business_v1_business_pb.ListBusinessesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBusinessesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/ListBusinesses',
        request,
        metadata || {},
        this.methodDescriptorListBusinesses,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/ListBusinesses',
    request,
    metadata || {},
    this.methodDescriptorListBusinesses);
  }

  methodDescriptorCreateBusinessLocation = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/CreateBusinessLocation',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.CreateBusinessLocationRequest,
    business_v1_business_pb.CreateBusinessLocationResponse,
    (request: business_v1_business_pb.CreateBusinessLocationRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.CreateBusinessLocationResponse.deserializeBinary
  );

  createBusinessLocation(
    request: business_v1_business_pb.CreateBusinessLocationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.CreateBusinessLocationResponse>;

  createBusinessLocation(
    request: business_v1_business_pb.CreateBusinessLocationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessLocationResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.CreateBusinessLocationResponse>;

  createBusinessLocation(
    request: business_v1_business_pb.CreateBusinessLocationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessLocationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/CreateBusinessLocation',
        request,
        metadata || {},
        this.methodDescriptorCreateBusinessLocation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/CreateBusinessLocation',
    request,
    metadata || {},
    this.methodDescriptorCreateBusinessLocation);
  }

  methodDescriptorGetBusinessLocation = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/GetBusinessLocation',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.GetBusinessLocationRequest,
    business_v1_business_pb.GetBusinessLocationResponse,
    (request: business_v1_business_pb.GetBusinessLocationRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.GetBusinessLocationResponse.deserializeBinary
  );

  getBusinessLocation(
    request: business_v1_business_pb.GetBusinessLocationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.GetBusinessLocationResponse>;

  getBusinessLocation(
    request: business_v1_business_pb.GetBusinessLocationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessLocationResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.GetBusinessLocationResponse>;

  getBusinessLocation(
    request: business_v1_business_pb.GetBusinessLocationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessLocationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/GetBusinessLocation',
        request,
        metadata || {},
        this.methodDescriptorGetBusinessLocation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/GetBusinessLocation',
    request,
    metadata || {},
    this.methodDescriptorGetBusinessLocation);
  }

  methodDescriptorUpdateBusinessLocation = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/UpdateBusinessLocation',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.UpdateBusinessLocationRequest,
    business_v1_business_pb.UpdateBusinessLocationResponse,
    (request: business_v1_business_pb.UpdateBusinessLocationRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.UpdateBusinessLocationResponse.deserializeBinary
  );

  updateBusinessLocation(
    request: business_v1_business_pb.UpdateBusinessLocationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.UpdateBusinessLocationResponse>;

  updateBusinessLocation(
    request: business_v1_business_pb.UpdateBusinessLocationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessLocationResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.UpdateBusinessLocationResponse>;

  updateBusinessLocation(
    request: business_v1_business_pb.UpdateBusinessLocationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessLocationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/UpdateBusinessLocation',
        request,
        metadata || {},
        this.methodDescriptorUpdateBusinessLocation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/UpdateBusinessLocation',
    request,
    metadata || {},
    this.methodDescriptorUpdateBusinessLocation);
  }

  methodDescriptorDeleteBusinessLocation = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/DeleteBusinessLocation',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.DeleteBusinessLocationRequest,
    google_protobuf_empty_pb.Empty,
    (request: business_v1_business_pb.DeleteBusinessLocationRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteBusinessLocation(
    request: business_v1_business_pb.DeleteBusinessLocationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteBusinessLocation(
    request: business_v1_business_pb.DeleteBusinessLocationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteBusinessLocation(
    request: business_v1_business_pb.DeleteBusinessLocationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/DeleteBusinessLocation',
        request,
        metadata || {},
        this.methodDescriptorDeleteBusinessLocation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/DeleteBusinessLocation',
    request,
    metadata || {},
    this.methodDescriptorDeleteBusinessLocation);
  }

  methodDescriptorListBusinessLocations = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/ListBusinessLocations',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.ListBusinessLocationsRequest,
    business_v1_business_pb.ListBusinessLocationsResponse,
    (request: business_v1_business_pb.ListBusinessLocationsRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.ListBusinessLocationsResponse.deserializeBinary
  );

  listBusinessLocations(
    request: business_v1_business_pb.ListBusinessLocationsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.ListBusinessLocationsResponse>;

  listBusinessLocations(
    request: business_v1_business_pb.ListBusinessLocationsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBusinessLocationsResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.ListBusinessLocationsResponse>;

  listBusinessLocations(
    request: business_v1_business_pb.ListBusinessLocationsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBusinessLocationsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/ListBusinessLocations',
        request,
        metadata || {},
        this.methodDescriptorListBusinessLocations,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/ListBusinessLocations',
    request,
    metadata || {},
    this.methodDescriptorListBusinessLocations);
  }

  methodDescriptorCreateBusinessMedia = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/CreateBusinessMedia',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.CreateBusinessMediaRequest,
    business_v1_business_pb.CreateBusinessMediaResponse,
    (request: business_v1_business_pb.CreateBusinessMediaRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.CreateBusinessMediaResponse.deserializeBinary
  );

  createBusinessMedia(
    request: business_v1_business_pb.CreateBusinessMediaRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.CreateBusinessMediaResponse>;

  createBusinessMedia(
    request: business_v1_business_pb.CreateBusinessMediaRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessMediaResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.CreateBusinessMediaResponse>;

  createBusinessMedia(
    request: business_v1_business_pb.CreateBusinessMediaRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessMediaResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/CreateBusinessMedia',
        request,
        metadata || {},
        this.methodDescriptorCreateBusinessMedia,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/CreateBusinessMedia',
    request,
    metadata || {},
    this.methodDescriptorCreateBusinessMedia);
  }

  methodDescriptorGetBusinessMedia = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/GetBusinessMedia',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.GetBusinessMediaRequest,
    business_v1_business_pb.GetBusinessMediaResponse,
    (request: business_v1_business_pb.GetBusinessMediaRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.GetBusinessMediaResponse.deserializeBinary
  );

  getBusinessMedia(
    request: business_v1_business_pb.GetBusinessMediaRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.GetBusinessMediaResponse>;

  getBusinessMedia(
    request: business_v1_business_pb.GetBusinessMediaRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessMediaResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.GetBusinessMediaResponse>;

  getBusinessMedia(
    request: business_v1_business_pb.GetBusinessMediaRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessMediaResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/GetBusinessMedia',
        request,
        metadata || {},
        this.methodDescriptorGetBusinessMedia,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/GetBusinessMedia',
    request,
    metadata || {},
    this.methodDescriptorGetBusinessMedia);
  }

  methodDescriptorUpdateBusinessMedia = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/UpdateBusinessMedia',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.UpdateBusinessMediaRequest,
    business_v1_business_pb.UpdateBusinessMediaResponse,
    (request: business_v1_business_pb.UpdateBusinessMediaRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.UpdateBusinessMediaResponse.deserializeBinary
  );

  updateBusinessMedia(
    request: business_v1_business_pb.UpdateBusinessMediaRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.UpdateBusinessMediaResponse>;

  updateBusinessMedia(
    request: business_v1_business_pb.UpdateBusinessMediaRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessMediaResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.UpdateBusinessMediaResponse>;

  updateBusinessMedia(
    request: business_v1_business_pb.UpdateBusinessMediaRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessMediaResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/UpdateBusinessMedia',
        request,
        metadata || {},
        this.methodDescriptorUpdateBusinessMedia,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/UpdateBusinessMedia',
    request,
    metadata || {},
    this.methodDescriptorUpdateBusinessMedia);
  }

  methodDescriptorDeleteBusinessMedia = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/DeleteBusinessMedia',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.DeleteBusinessMediaRequest,
    google_protobuf_empty_pb.Empty,
    (request: business_v1_business_pb.DeleteBusinessMediaRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteBusinessMedia(
    request: business_v1_business_pb.DeleteBusinessMediaRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteBusinessMedia(
    request: business_v1_business_pb.DeleteBusinessMediaRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteBusinessMedia(
    request: business_v1_business_pb.DeleteBusinessMediaRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/DeleteBusinessMedia',
        request,
        metadata || {},
        this.methodDescriptorDeleteBusinessMedia,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/DeleteBusinessMedia',
    request,
    metadata || {},
    this.methodDescriptorDeleteBusinessMedia);
  }

  methodDescriptorListBusinessMedia = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/ListBusinessMedia',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.ListBusinessMediaRequest,
    business_v1_business_pb.ListBusinessMediaResponse,
    (request: business_v1_business_pb.ListBusinessMediaRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.ListBusinessMediaResponse.deserializeBinary
  );

  listBusinessMedia(
    request: business_v1_business_pb.ListBusinessMediaRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.ListBusinessMediaResponse>;

  listBusinessMedia(
    request: business_v1_business_pb.ListBusinessMediaRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBusinessMediaResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.ListBusinessMediaResponse>;

  listBusinessMedia(
    request: business_v1_business_pb.ListBusinessMediaRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBusinessMediaResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/ListBusinessMedia',
        request,
        metadata || {},
        this.methodDescriptorListBusinessMedia,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/ListBusinessMedia',
    request,
    metadata || {},
    this.methodDescriptorListBusinessMedia);
  }

  methodDescriptorCreateSocialPlatform = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/CreateSocialPlatform',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.CreateSocialPlatformRequest,
    business_v1_business_pb.CreateSocialPlatformResponse,
    (request: business_v1_business_pb.CreateSocialPlatformRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.CreateSocialPlatformResponse.deserializeBinary
  );

  createSocialPlatform(
    request: business_v1_business_pb.CreateSocialPlatformRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.CreateSocialPlatformResponse>;

  createSocialPlatform(
    request: business_v1_business_pb.CreateSocialPlatformRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateSocialPlatformResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.CreateSocialPlatformResponse>;

  createSocialPlatform(
    request: business_v1_business_pb.CreateSocialPlatformRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateSocialPlatformResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/CreateSocialPlatform',
        request,
        metadata || {},
        this.methodDescriptorCreateSocialPlatform,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/CreateSocialPlatform',
    request,
    metadata || {},
    this.methodDescriptorCreateSocialPlatform);
  }

  methodDescriptorGetSocialPlatform = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/GetSocialPlatform',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.GetSocialPlatformRequest,
    business_v1_business_pb.GetSocialPlatformResponse,
    (request: business_v1_business_pb.GetSocialPlatformRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.GetSocialPlatformResponse.deserializeBinary
  );

  getSocialPlatform(
    request: business_v1_business_pb.GetSocialPlatformRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.GetSocialPlatformResponse>;

  getSocialPlatform(
    request: business_v1_business_pb.GetSocialPlatformRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetSocialPlatformResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.GetSocialPlatformResponse>;

  getSocialPlatform(
    request: business_v1_business_pb.GetSocialPlatformRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetSocialPlatformResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/GetSocialPlatform',
        request,
        metadata || {},
        this.methodDescriptorGetSocialPlatform,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/GetSocialPlatform',
    request,
    metadata || {},
    this.methodDescriptorGetSocialPlatform);
  }

  methodDescriptorUpdateSocialPlatform = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/UpdateSocialPlatform',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.UpdateSocialPlatformRequest,
    business_v1_business_pb.UpdateSocialPlatformResponse,
    (request: business_v1_business_pb.UpdateSocialPlatformRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.UpdateSocialPlatformResponse.deserializeBinary
  );

  updateSocialPlatform(
    request: business_v1_business_pb.UpdateSocialPlatformRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.UpdateSocialPlatformResponse>;

  updateSocialPlatform(
    request: business_v1_business_pb.UpdateSocialPlatformRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateSocialPlatformResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.UpdateSocialPlatformResponse>;

  updateSocialPlatform(
    request: business_v1_business_pb.UpdateSocialPlatformRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateSocialPlatformResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/UpdateSocialPlatform',
        request,
        metadata || {},
        this.methodDescriptorUpdateSocialPlatform,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/UpdateSocialPlatform',
    request,
    metadata || {},
    this.methodDescriptorUpdateSocialPlatform);
  }

  methodDescriptorDeleteSocialPlatform = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/DeleteSocialPlatform',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.DeleteSocialPlatformRequest,
    google_protobuf_empty_pb.Empty,
    (request: business_v1_business_pb.DeleteSocialPlatformRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteSocialPlatform(
    request: business_v1_business_pb.DeleteSocialPlatformRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteSocialPlatform(
    request: business_v1_business_pb.DeleteSocialPlatformRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteSocialPlatform(
    request: business_v1_business_pb.DeleteSocialPlatformRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/DeleteSocialPlatform',
        request,
        metadata || {},
        this.methodDescriptorDeleteSocialPlatform,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/DeleteSocialPlatform',
    request,
    metadata || {},
    this.methodDescriptorDeleteSocialPlatform);
  }

  methodDescriptorListSocialPlatforms = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/ListSocialPlatforms',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.ListSocialPlatformsRequest,
    business_v1_business_pb.ListSocialPlatformsResponse,
    (request: business_v1_business_pb.ListSocialPlatformsRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.ListSocialPlatformsResponse.deserializeBinary
  );

  listSocialPlatforms(
    request: business_v1_business_pb.ListSocialPlatformsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.ListSocialPlatformsResponse>;

  listSocialPlatforms(
    request: business_v1_business_pb.ListSocialPlatformsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListSocialPlatformsResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.ListSocialPlatformsResponse>;

  listSocialPlatforms(
    request: business_v1_business_pb.ListSocialPlatformsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListSocialPlatformsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/ListSocialPlatforms',
        request,
        metadata || {},
        this.methodDescriptorListSocialPlatforms,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/ListSocialPlatforms',
    request,
    metadata || {},
    this.methodDescriptorListSocialPlatforms);
  }

  methodDescriptorCreateCategory = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/CreateCategory',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.CreateCategoryRequest,
    business_v1_business_pb.CreateCategoryResponse,
    (request: business_v1_business_pb.CreateCategoryRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.CreateCategoryResponse.deserializeBinary
  );

  createCategory(
    request: business_v1_business_pb.CreateCategoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.CreateCategoryResponse>;

  createCategory(
    request: business_v1_business_pb.CreateCategoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateCategoryResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.CreateCategoryResponse>;

  createCategory(
    request: business_v1_business_pb.CreateCategoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateCategoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/CreateCategory',
        request,
        metadata || {},
        this.methodDescriptorCreateCategory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/CreateCategory',
    request,
    metadata || {},
    this.methodDescriptorCreateCategory);
  }

  methodDescriptorGetCategory = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/GetCategory',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.GetCategoryRequest,
    business_v1_business_pb.GetCategoryResponse,
    (request: business_v1_business_pb.GetCategoryRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.GetCategoryResponse.deserializeBinary
  );

  getCategory(
    request: business_v1_business_pb.GetCategoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.GetCategoryResponse>;

  getCategory(
    request: business_v1_business_pb.GetCategoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetCategoryResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.GetCategoryResponse>;

  getCategory(
    request: business_v1_business_pb.GetCategoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetCategoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/GetCategory',
        request,
        metadata || {},
        this.methodDescriptorGetCategory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/GetCategory',
    request,
    metadata || {},
    this.methodDescriptorGetCategory);
  }

  methodDescriptorUpdateCategory = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/UpdateCategory',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.UpdateCategoryRequest,
    business_v1_business_pb.UpdateCategoryResponse,
    (request: business_v1_business_pb.UpdateCategoryRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.UpdateCategoryResponse.deserializeBinary
  );

  updateCategory(
    request: business_v1_business_pb.UpdateCategoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.UpdateCategoryResponse>;

  updateCategory(
    request: business_v1_business_pb.UpdateCategoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateCategoryResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.UpdateCategoryResponse>;

  updateCategory(
    request: business_v1_business_pb.UpdateCategoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateCategoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/UpdateCategory',
        request,
        metadata || {},
        this.methodDescriptorUpdateCategory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/UpdateCategory',
    request,
    metadata || {},
    this.methodDescriptorUpdateCategory);
  }

  methodDescriptorDeleteCategory = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/DeleteCategory',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.DeleteCategoryRequest,
    google_protobuf_empty_pb.Empty,
    (request: business_v1_business_pb.DeleteCategoryRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteCategory(
    request: business_v1_business_pb.DeleteCategoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteCategory(
    request: business_v1_business_pb.DeleteCategoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteCategory(
    request: business_v1_business_pb.DeleteCategoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/DeleteCategory',
        request,
        metadata || {},
        this.methodDescriptorDeleteCategory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/DeleteCategory',
    request,
    metadata || {},
    this.methodDescriptorDeleteCategory);
  }

  methodDescriptorListCategories = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/ListCategories',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.ListCategoriesRequest,
    business_v1_business_pb.ListCategoriesResponse,
    (request: business_v1_business_pb.ListCategoriesRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.ListCategoriesResponse.deserializeBinary
  );

  listCategories(
    request: business_v1_business_pb.ListCategoriesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.ListCategoriesResponse>;

  listCategories(
    request: business_v1_business_pb.ListCategoriesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListCategoriesResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.ListCategoriesResponse>;

  listCategories(
    request: business_v1_business_pb.ListCategoriesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListCategoriesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/ListCategories',
        request,
        metadata || {},
        this.methodDescriptorListCategories,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/ListCategories',
    request,
    metadata || {},
    this.methodDescriptorListCategories);
  }

  methodDescriptorCreateBusinessSocialAccount = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/CreateBusinessSocialAccount',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.CreateBusinessSocialAccountRequest,
    business_v1_business_pb.CreateBusinessSocialAccountResponse,
    (request: business_v1_business_pb.CreateBusinessSocialAccountRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.CreateBusinessSocialAccountResponse.deserializeBinary
  );

  createBusinessSocialAccount(
    request: business_v1_business_pb.CreateBusinessSocialAccountRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.CreateBusinessSocialAccountResponse>;

  createBusinessSocialAccount(
    request: business_v1_business_pb.CreateBusinessSocialAccountRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessSocialAccountResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.CreateBusinessSocialAccountResponse>;

  createBusinessSocialAccount(
    request: business_v1_business_pb.CreateBusinessSocialAccountRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessSocialAccountResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/CreateBusinessSocialAccount',
        request,
        metadata || {},
        this.methodDescriptorCreateBusinessSocialAccount,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/CreateBusinessSocialAccount',
    request,
    metadata || {},
    this.methodDescriptorCreateBusinessSocialAccount);
  }

  methodDescriptorGetBusinessSocialAccount = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/GetBusinessSocialAccount',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.GetBusinessSocialAccountRequest,
    business_v1_business_pb.GetBusinessSocialAccountResponse,
    (request: business_v1_business_pb.GetBusinessSocialAccountRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.GetBusinessSocialAccountResponse.deserializeBinary
  );

  getBusinessSocialAccount(
    request: business_v1_business_pb.GetBusinessSocialAccountRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.GetBusinessSocialAccountResponse>;

  getBusinessSocialAccount(
    request: business_v1_business_pb.GetBusinessSocialAccountRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessSocialAccountResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.GetBusinessSocialAccountResponse>;

  getBusinessSocialAccount(
    request: business_v1_business_pb.GetBusinessSocialAccountRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessSocialAccountResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/GetBusinessSocialAccount',
        request,
        metadata || {},
        this.methodDescriptorGetBusinessSocialAccount,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/GetBusinessSocialAccount',
    request,
    metadata || {},
    this.methodDescriptorGetBusinessSocialAccount);
  }

  methodDescriptorUpdateBusinessSocialAccount = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/UpdateBusinessSocialAccount',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.UpdateBusinessSocialAccountRequest,
    business_v1_business_pb.UpdateBusinessSocialAccountResponse,
    (request: business_v1_business_pb.UpdateBusinessSocialAccountRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.UpdateBusinessSocialAccountResponse.deserializeBinary
  );

  updateBusinessSocialAccount(
    request: business_v1_business_pb.UpdateBusinessSocialAccountRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.UpdateBusinessSocialAccountResponse>;

  updateBusinessSocialAccount(
    request: business_v1_business_pb.UpdateBusinessSocialAccountRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessSocialAccountResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.UpdateBusinessSocialAccountResponse>;

  updateBusinessSocialAccount(
    request: business_v1_business_pb.UpdateBusinessSocialAccountRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessSocialAccountResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/UpdateBusinessSocialAccount',
        request,
        metadata || {},
        this.methodDescriptorUpdateBusinessSocialAccount,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/UpdateBusinessSocialAccount',
    request,
    metadata || {},
    this.methodDescriptorUpdateBusinessSocialAccount);
  }

  methodDescriptorDeleteBusinessSocialAccount = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/DeleteBusinessSocialAccount',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.DeleteBusinessSocialAccountRequest,
    google_protobuf_empty_pb.Empty,
    (request: business_v1_business_pb.DeleteBusinessSocialAccountRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteBusinessSocialAccount(
    request: business_v1_business_pb.DeleteBusinessSocialAccountRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteBusinessSocialAccount(
    request: business_v1_business_pb.DeleteBusinessSocialAccountRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteBusinessSocialAccount(
    request: business_v1_business_pb.DeleteBusinessSocialAccountRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/DeleteBusinessSocialAccount',
        request,
        metadata || {},
        this.methodDescriptorDeleteBusinessSocialAccount,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/DeleteBusinessSocialAccount',
    request,
    metadata || {},
    this.methodDescriptorDeleteBusinessSocialAccount);
  }

  methodDescriptorListBusinessSocialAccounts = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/ListBusinessSocialAccounts',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.ListBusinessSocialAccountsRequest,
    business_v1_business_pb.ListBusinessSocialAccountsResponse,
    (request: business_v1_business_pb.ListBusinessSocialAccountsRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.ListBusinessSocialAccountsResponse.deserializeBinary
  );

  listBusinessSocialAccounts(
    request: business_v1_business_pb.ListBusinessSocialAccountsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.ListBusinessSocialAccountsResponse>;

  listBusinessSocialAccounts(
    request: business_v1_business_pb.ListBusinessSocialAccountsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBusinessSocialAccountsResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.ListBusinessSocialAccountsResponse>;

  listBusinessSocialAccounts(
    request: business_v1_business_pb.ListBusinessSocialAccountsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBusinessSocialAccountsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/ListBusinessSocialAccounts',
        request,
        metadata || {},
        this.methodDescriptorListBusinessSocialAccounts,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/ListBusinessSocialAccounts',
    request,
    metadata || {},
    this.methodDescriptorListBusinessSocialAccounts);
  }

  methodDescriptorCreateBusinessReview = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/CreateBusinessReview',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.CreateBusinessReviewRequest,
    business_v1_business_pb.CreateBusinessReviewResponse,
    (request: business_v1_business_pb.CreateBusinessReviewRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.CreateBusinessReviewResponse.deserializeBinary
  );

  createBusinessReview(
    request: business_v1_business_pb.CreateBusinessReviewRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.CreateBusinessReviewResponse>;

  createBusinessReview(
    request: business_v1_business_pb.CreateBusinessReviewRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessReviewResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.CreateBusinessReviewResponse>;

  createBusinessReview(
    request: business_v1_business_pb.CreateBusinessReviewRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessReviewResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/CreateBusinessReview',
        request,
        metadata || {},
        this.methodDescriptorCreateBusinessReview,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/CreateBusinessReview',
    request,
    metadata || {},
    this.methodDescriptorCreateBusinessReview);
  }

  methodDescriptorGetBusinessReview = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/GetBusinessReview',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.GetBusinessReviewRequest,
    business_v1_business_pb.GetBusinessReviewResponse,
    (request: business_v1_business_pb.GetBusinessReviewRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.GetBusinessReviewResponse.deserializeBinary
  );

  getBusinessReview(
    request: business_v1_business_pb.GetBusinessReviewRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.GetBusinessReviewResponse>;

  getBusinessReview(
    request: business_v1_business_pb.GetBusinessReviewRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessReviewResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.GetBusinessReviewResponse>;

  getBusinessReview(
    request: business_v1_business_pb.GetBusinessReviewRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessReviewResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/GetBusinessReview',
        request,
        metadata || {},
        this.methodDescriptorGetBusinessReview,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/GetBusinessReview',
    request,
    metadata || {},
    this.methodDescriptorGetBusinessReview);
  }

  methodDescriptorUpdateBusinessReview = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/UpdateBusinessReview',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.UpdateBusinessReviewRequest,
    business_v1_business_pb.UpdateBusinessReviewResponse,
    (request: business_v1_business_pb.UpdateBusinessReviewRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.UpdateBusinessReviewResponse.deserializeBinary
  );

  updateBusinessReview(
    request: business_v1_business_pb.UpdateBusinessReviewRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.UpdateBusinessReviewResponse>;

  updateBusinessReview(
    request: business_v1_business_pb.UpdateBusinessReviewRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessReviewResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.UpdateBusinessReviewResponse>;

  updateBusinessReview(
    request: business_v1_business_pb.UpdateBusinessReviewRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessReviewResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/UpdateBusinessReview',
        request,
        metadata || {},
        this.methodDescriptorUpdateBusinessReview,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/UpdateBusinessReview',
    request,
    metadata || {},
    this.methodDescriptorUpdateBusinessReview);
  }

  methodDescriptorDeleteBusinessReview = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/DeleteBusinessReview',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.DeleteBusinessReviewRequest,
    google_protobuf_empty_pb.Empty,
    (request: business_v1_business_pb.DeleteBusinessReviewRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteBusinessReview(
    request: business_v1_business_pb.DeleteBusinessReviewRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteBusinessReview(
    request: business_v1_business_pb.DeleteBusinessReviewRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteBusinessReview(
    request: business_v1_business_pb.DeleteBusinessReviewRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/DeleteBusinessReview',
        request,
        metadata || {},
        this.methodDescriptorDeleteBusinessReview,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/DeleteBusinessReview',
    request,
    metadata || {},
    this.methodDescriptorDeleteBusinessReview);
  }

  methodDescriptorListBusinessReviews = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/ListBusinessReviews',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.ListBusinessReviewsRequest,
    business_v1_business_pb.ListBusinessReviewsResponse,
    (request: business_v1_business_pb.ListBusinessReviewsRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.ListBusinessReviewsResponse.deserializeBinary
  );

  listBusinessReviews(
    request: business_v1_business_pb.ListBusinessReviewsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.ListBusinessReviewsResponse>;

  listBusinessReviews(
    request: business_v1_business_pb.ListBusinessReviewsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBusinessReviewsResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.ListBusinessReviewsResponse>;

  listBusinessReviews(
    request: business_v1_business_pb.ListBusinessReviewsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBusinessReviewsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/ListBusinessReviews',
        request,
        metadata || {},
        this.methodDescriptorListBusinessReviews,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/ListBusinessReviews',
    request,
    metadata || {},
    this.methodDescriptorListBusinessReviews);
  }

  methodDescriptorCreateBusinessMembership = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/CreateBusinessMembership',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.CreateBusinessMembershipRequest,
    business_v1_business_pb.CreateBusinessMembershipResponse,
    (request: business_v1_business_pb.CreateBusinessMembershipRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.CreateBusinessMembershipResponse.deserializeBinary
  );

  createBusinessMembership(
    request: business_v1_business_pb.CreateBusinessMembershipRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.CreateBusinessMembershipResponse>;

  createBusinessMembership(
    request: business_v1_business_pb.CreateBusinessMembershipRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessMembershipResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.CreateBusinessMembershipResponse>;

  createBusinessMembership(
    request: business_v1_business_pb.CreateBusinessMembershipRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessMembershipResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/CreateBusinessMembership',
        request,
        metadata || {},
        this.methodDescriptorCreateBusinessMembership,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/CreateBusinessMembership',
    request,
    metadata || {},
    this.methodDescriptorCreateBusinessMembership);
  }

  methodDescriptorGetBusinessMembership = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/GetBusinessMembership',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.GetBusinessMembershipRequest,
    business_v1_business_pb.GetBusinessMembershipResponse,
    (request: business_v1_business_pb.GetBusinessMembershipRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.GetBusinessMembershipResponse.deserializeBinary
  );

  getBusinessMembership(
    request: business_v1_business_pb.GetBusinessMembershipRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.GetBusinessMembershipResponse>;

  getBusinessMembership(
    request: business_v1_business_pb.GetBusinessMembershipRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessMembershipResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.GetBusinessMembershipResponse>;

  getBusinessMembership(
    request: business_v1_business_pb.GetBusinessMembershipRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessMembershipResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/GetBusinessMembership',
        request,
        metadata || {},
        this.methodDescriptorGetBusinessMembership,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/GetBusinessMembership',
    request,
    metadata || {},
    this.methodDescriptorGetBusinessMembership);
  }

  methodDescriptorUpdateBusinessMembership = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/UpdateBusinessMembership',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.UpdateBusinessMembershipRequest,
    business_v1_business_pb.UpdateBusinessMembershipResponse,
    (request: business_v1_business_pb.UpdateBusinessMembershipRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.UpdateBusinessMembershipResponse.deserializeBinary
  );

  updateBusinessMembership(
    request: business_v1_business_pb.UpdateBusinessMembershipRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.UpdateBusinessMembershipResponse>;

  updateBusinessMembership(
    request: business_v1_business_pb.UpdateBusinessMembershipRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessMembershipResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.UpdateBusinessMembershipResponse>;

  updateBusinessMembership(
    request: business_v1_business_pb.UpdateBusinessMembershipRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessMembershipResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/UpdateBusinessMembership',
        request,
        metadata || {},
        this.methodDescriptorUpdateBusinessMembership,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/UpdateBusinessMembership',
    request,
    metadata || {},
    this.methodDescriptorUpdateBusinessMembership);
  }

  methodDescriptorDeleteBusinessMembership = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/DeleteBusinessMembership',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.DeleteBusinessMembershipRequest,
    google_protobuf_empty_pb.Empty,
    (request: business_v1_business_pb.DeleteBusinessMembershipRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteBusinessMembership(
    request: business_v1_business_pb.DeleteBusinessMembershipRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteBusinessMembership(
    request: business_v1_business_pb.DeleteBusinessMembershipRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteBusinessMembership(
    request: business_v1_business_pb.DeleteBusinessMembershipRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/DeleteBusinessMembership',
        request,
        metadata || {},
        this.methodDescriptorDeleteBusinessMembership,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/DeleteBusinessMembership',
    request,
    metadata || {},
    this.methodDescriptorDeleteBusinessMembership);
  }

  methodDescriptorListBusinessMemberships = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/ListBusinessMemberships',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.ListBusinessMembershipsRequest,
    business_v1_business_pb.ListBusinessMembershipsResponse,
    (request: business_v1_business_pb.ListBusinessMembershipsRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.ListBusinessMembershipsResponse.deserializeBinary
  );

  listBusinessMemberships(
    request: business_v1_business_pb.ListBusinessMembershipsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.ListBusinessMembershipsResponse>;

  listBusinessMemberships(
    request: business_v1_business_pb.ListBusinessMembershipsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBusinessMembershipsResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.ListBusinessMembershipsResponse>;

  listBusinessMemberships(
    request: business_v1_business_pb.ListBusinessMembershipsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBusinessMembershipsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/ListBusinessMemberships',
        request,
        metadata || {},
        this.methodDescriptorListBusinessMemberships,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/ListBusinessMemberships',
    request,
    metadata || {},
    this.methodDescriptorListBusinessMemberships);
  }

  methodDescriptorCreateBrand = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/CreateBrand',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.CreateBrandRequest,
    business_v1_business_pb.CreateBrandResponse,
    (request: business_v1_business_pb.CreateBrandRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.CreateBrandResponse.deserializeBinary
  );

  createBrand(
    request: business_v1_business_pb.CreateBrandRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.CreateBrandResponse>;

  createBrand(
    request: business_v1_business_pb.CreateBrandRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBrandResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.CreateBrandResponse>;

  createBrand(
    request: business_v1_business_pb.CreateBrandRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBrandResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/CreateBrand',
        request,
        metadata || {},
        this.methodDescriptorCreateBrand,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/CreateBrand',
    request,
    metadata || {},
    this.methodDescriptorCreateBrand);
  }

  methodDescriptorGetBrand = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/GetBrand',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.GetBrandRequest,
    business_v1_business_pb.GetBrandResponse,
    (request: business_v1_business_pb.GetBrandRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.GetBrandResponse.deserializeBinary
  );

  getBrand(
    request: business_v1_business_pb.GetBrandRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.GetBrandResponse>;

  getBrand(
    request: business_v1_business_pb.GetBrandRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBrandResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.GetBrandResponse>;

  getBrand(
    request: business_v1_business_pb.GetBrandRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBrandResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/GetBrand',
        request,
        metadata || {},
        this.methodDescriptorGetBrand,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/GetBrand',
    request,
    metadata || {},
    this.methodDescriptorGetBrand);
  }

  methodDescriptorUpdateBrand = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/UpdateBrand',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.UpdateBrandRequest,
    business_v1_business_pb.UpdateBrandResponse,
    (request: business_v1_business_pb.UpdateBrandRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.UpdateBrandResponse.deserializeBinary
  );

  updateBrand(
    request: business_v1_business_pb.UpdateBrandRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.UpdateBrandResponse>;

  updateBrand(
    request: business_v1_business_pb.UpdateBrandRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBrandResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.UpdateBrandResponse>;

  updateBrand(
    request: business_v1_business_pb.UpdateBrandRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBrandResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/UpdateBrand',
        request,
        metadata || {},
        this.methodDescriptorUpdateBrand,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/UpdateBrand',
    request,
    metadata || {},
    this.methodDescriptorUpdateBrand);
  }

  methodDescriptorDeleteBrand = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/DeleteBrand',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.DeleteBrandRequest,
    google_protobuf_empty_pb.Empty,
    (request: business_v1_business_pb.DeleteBrandRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteBrand(
    request: business_v1_business_pb.DeleteBrandRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteBrand(
    request: business_v1_business_pb.DeleteBrandRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteBrand(
    request: business_v1_business_pb.DeleteBrandRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/DeleteBrand',
        request,
        metadata || {},
        this.methodDescriptorDeleteBrand,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/DeleteBrand',
    request,
    metadata || {},
    this.methodDescriptorDeleteBrand);
  }

  methodDescriptorListBrands = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/ListBrands',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.ListBrandsRequest,
    business_v1_business_pb.ListBrandsResponse,
    (request: business_v1_business_pb.ListBrandsRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.ListBrandsResponse.deserializeBinary
  );

  listBrands(
    request: business_v1_business_pb.ListBrandsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.ListBrandsResponse>;

  listBrands(
    request: business_v1_business_pb.ListBrandsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBrandsResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.ListBrandsResponse>;

  listBrands(
    request: business_v1_business_pb.ListBrandsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBrandsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/ListBrands',
        request,
        metadata || {},
        this.methodDescriptorListBrands,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/ListBrands',
    request,
    metadata || {},
    this.methodDescriptorListBrands);
  }

  methodDescriptorSearchBrands = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/SearchBrands',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.SearchBrandsRequest,
    business_v1_business_pb.SearchBrandsResponse,
    (request: business_v1_business_pb.SearchBrandsRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.SearchBrandsResponse.deserializeBinary
  );

  searchBrands(
    request: business_v1_business_pb.SearchBrandsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.SearchBrandsResponse>;

  searchBrands(
    request: business_v1_business_pb.SearchBrandsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.SearchBrandsResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.SearchBrandsResponse>;

  searchBrands(
    request: business_v1_business_pb.SearchBrandsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.SearchBrandsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/SearchBrands',
        request,
        metadata || {},
        this.methodDescriptorSearchBrands,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/SearchBrands',
    request,
    metadata || {},
    this.methodDescriptorSearchBrands);
  }

  methodDescriptorCreateBusinessBrand = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/CreateBusinessBrand',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.CreateBusinessBrandRequest,
    business_v1_business_pb.CreateBusinessBrandResponse,
    (request: business_v1_business_pb.CreateBusinessBrandRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.CreateBusinessBrandResponse.deserializeBinary
  );

  createBusinessBrand(
    request: business_v1_business_pb.CreateBusinessBrandRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.CreateBusinessBrandResponse>;

  createBusinessBrand(
    request: business_v1_business_pb.CreateBusinessBrandRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessBrandResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.CreateBusinessBrandResponse>;

  createBusinessBrand(
    request: business_v1_business_pb.CreateBusinessBrandRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessBrandResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/CreateBusinessBrand',
        request,
        metadata || {},
        this.methodDescriptorCreateBusinessBrand,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/CreateBusinessBrand',
    request,
    metadata || {},
    this.methodDescriptorCreateBusinessBrand);
  }

  methodDescriptorGetBusinessBrand = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/GetBusinessBrand',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.GetBusinessBrandRequest,
    business_v1_business_pb.GetBusinessBrandResponse,
    (request: business_v1_business_pb.GetBusinessBrandRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.GetBusinessBrandResponse.deserializeBinary
  );

  getBusinessBrand(
    request: business_v1_business_pb.GetBusinessBrandRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.GetBusinessBrandResponse>;

  getBusinessBrand(
    request: business_v1_business_pb.GetBusinessBrandRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessBrandResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.GetBusinessBrandResponse>;

  getBusinessBrand(
    request: business_v1_business_pb.GetBusinessBrandRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessBrandResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/GetBusinessBrand',
        request,
        metadata || {},
        this.methodDescriptorGetBusinessBrand,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/GetBusinessBrand',
    request,
    metadata || {},
    this.methodDescriptorGetBusinessBrand);
  }

  methodDescriptorUpdateBusinessBrand = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/UpdateBusinessBrand',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.UpdateBusinessBrandRequest,
    business_v1_business_pb.UpdateBusinessBrandResponse,
    (request: business_v1_business_pb.UpdateBusinessBrandRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.UpdateBusinessBrandResponse.deserializeBinary
  );

  updateBusinessBrand(
    request: business_v1_business_pb.UpdateBusinessBrandRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.UpdateBusinessBrandResponse>;

  updateBusinessBrand(
    request: business_v1_business_pb.UpdateBusinessBrandRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessBrandResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.UpdateBusinessBrandResponse>;

  updateBusinessBrand(
    request: business_v1_business_pb.UpdateBusinessBrandRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessBrandResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/UpdateBusinessBrand',
        request,
        metadata || {},
        this.methodDescriptorUpdateBusinessBrand,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/UpdateBusinessBrand',
    request,
    metadata || {},
    this.methodDescriptorUpdateBusinessBrand);
  }

  methodDescriptorDeleteBusinessBrand = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/DeleteBusinessBrand',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.DeleteBusinessBrandRequest,
    google_protobuf_empty_pb.Empty,
    (request: business_v1_business_pb.DeleteBusinessBrandRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteBusinessBrand(
    request: business_v1_business_pb.DeleteBusinessBrandRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteBusinessBrand(
    request: business_v1_business_pb.DeleteBusinessBrandRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteBusinessBrand(
    request: business_v1_business_pb.DeleteBusinessBrandRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/DeleteBusinessBrand',
        request,
        metadata || {},
        this.methodDescriptorDeleteBusinessBrand,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/DeleteBusinessBrand',
    request,
    metadata || {},
    this.methodDescriptorDeleteBusinessBrand);
  }

  methodDescriptorListBusinessBrands = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/ListBusinessBrands',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.ListBusinessBrandsRequest,
    business_v1_business_pb.ListBusinessBrandsResponse,
    (request: business_v1_business_pb.ListBusinessBrandsRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.ListBusinessBrandsResponse.deserializeBinary
  );

  listBusinessBrands(
    request: business_v1_business_pb.ListBusinessBrandsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.ListBusinessBrandsResponse>;

  listBusinessBrands(
    request: business_v1_business_pb.ListBusinessBrandsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBusinessBrandsResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.ListBusinessBrandsResponse>;

  listBusinessBrands(
    request: business_v1_business_pb.ListBusinessBrandsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.ListBusinessBrandsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/ListBusinessBrands',
        request,
        metadata || {},
        this.methodDescriptorListBusinessBrands,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/ListBusinessBrands',
    request,
    metadata || {},
    this.methodDescriptorListBusinessBrands);
  }

  methodDescriptorAddBusinessToBrand = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/AddBusinessToBrand',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.AddBusinessToBrandRequest,
    business_v1_business_pb.AddBusinessToBrandResponse,
    (request: business_v1_business_pb.AddBusinessToBrandRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.AddBusinessToBrandResponse.deserializeBinary
  );

  addBusinessToBrand(
    request: business_v1_business_pb.AddBusinessToBrandRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.AddBusinessToBrandResponse>;

  addBusinessToBrand(
    request: business_v1_business_pb.AddBusinessToBrandRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.AddBusinessToBrandResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.AddBusinessToBrandResponse>;

  addBusinessToBrand(
    request: business_v1_business_pb.AddBusinessToBrandRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.AddBusinessToBrandResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/AddBusinessToBrand',
        request,
        metadata || {},
        this.methodDescriptorAddBusinessToBrand,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/AddBusinessToBrand',
    request,
    metadata || {},
    this.methodDescriptorAddBusinessToBrand);
  }

  methodDescriptorRemoveBusinessFromBrand = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/RemoveBusinessFromBrand',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.RemoveBusinessFromBrandRequest,
    google_protobuf_empty_pb.Empty,
    (request: business_v1_business_pb.RemoveBusinessFromBrandRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  removeBusinessFromBrand(
    request: business_v1_business_pb.RemoveBusinessFromBrandRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  removeBusinessFromBrand(
    request: business_v1_business_pb.RemoveBusinessFromBrandRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  removeBusinessFromBrand(
    request: business_v1_business_pb.RemoveBusinessFromBrandRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/RemoveBusinessFromBrand',
        request,
        metadata || {},
        this.methodDescriptorRemoveBusinessFromBrand,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/RemoveBusinessFromBrand',
    request,
    metadata || {},
    this.methodDescriptorRemoveBusinessFromBrand);
  }

  methodDescriptorCreateBusinessRelation = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/CreateBusinessRelation',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.CreateBusinessRelationRequest,
    business_v1_business_pb.CreateBusinessRelationResponse,
    (request: business_v1_business_pb.CreateBusinessRelationRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.CreateBusinessRelationResponse.deserializeBinary
  );

  createBusinessRelation(
    request: business_v1_business_pb.CreateBusinessRelationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.CreateBusinessRelationResponse>;

  createBusinessRelation(
    request: business_v1_business_pb.CreateBusinessRelationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessRelationResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.CreateBusinessRelationResponse>;

  createBusinessRelation(
    request: business_v1_business_pb.CreateBusinessRelationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.CreateBusinessRelationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/CreateBusinessRelation',
        request,
        metadata || {},
        this.methodDescriptorCreateBusinessRelation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/CreateBusinessRelation',
    request,
    metadata || {},
    this.methodDescriptorCreateBusinessRelation);
  }

  methodDescriptorGetBusinessRelation = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/GetBusinessRelation',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.GetBusinessRelationRequest,
    business_v1_business_pb.GetBusinessRelationResponse,
    (request: business_v1_business_pb.GetBusinessRelationRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.GetBusinessRelationResponse.deserializeBinary
  );

  getBusinessRelation(
    request: business_v1_business_pb.GetBusinessRelationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.GetBusinessRelationResponse>;

  getBusinessRelation(
    request: business_v1_business_pb.GetBusinessRelationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessRelationResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.GetBusinessRelationResponse>;

  getBusinessRelation(
    request: business_v1_business_pb.GetBusinessRelationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.GetBusinessRelationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/GetBusinessRelation',
        request,
        metadata || {},
        this.methodDescriptorGetBusinessRelation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/GetBusinessRelation',
    request,
    metadata || {},
    this.methodDescriptorGetBusinessRelation);
  }

  methodDescriptorUpdateBusinessRelation = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/UpdateBusinessRelation',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.UpdateBusinessRelationRequest,
    business_v1_business_pb.UpdateBusinessRelationResponse,
    (request: business_v1_business_pb.UpdateBusinessRelationRequest) => {
      return request.serializeBinary();
    },
    business_v1_business_pb.UpdateBusinessRelationResponse.deserializeBinary
  );

  updateBusinessRelation(
    request: business_v1_business_pb.UpdateBusinessRelationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_business_pb.UpdateBusinessRelationResponse>;

  updateBusinessRelation(
    request: business_v1_business_pb.UpdateBusinessRelationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessRelationResponse) => void): grpcWeb.ClientReadableStream<business_v1_business_pb.UpdateBusinessRelationResponse>;

  updateBusinessRelation(
    request: business_v1_business_pb.UpdateBusinessRelationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_business_pb.UpdateBusinessRelationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/UpdateBusinessRelation',
        request,
        metadata || {},
        this.methodDescriptorUpdateBusinessRelation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/UpdateBusinessRelation',
    request,
    metadata || {},
    this.methodDescriptorUpdateBusinessRelation);
  }

  methodDescriptorDeleteBusinessRelation = new grpcWeb.MethodDescriptor(
    '/business.v1.BusinessService/DeleteBusinessRelation',
    grpcWeb.MethodType.UNARY,
    business_v1_business_pb.DeleteBusinessRelationRequest,
    google_protobuf_empty_pb.Empty,
    (request: business_v1_business_pb.DeleteBusinessRelationRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteBusinessRelation(
    request: business_v1_business_pb.DeleteBusinessRelationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteBusinessRelation(
    request: business_v1_business_pb.DeleteBusinessRelationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteBusinessRelation(
    request: business_v1_business_pb.DeleteBusinessRelationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.BusinessService/DeleteBusinessRelation',
        request,
        metadata || {},
        this.methodDescriptorDeleteBusinessRelation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.BusinessService/DeleteBusinessRelation',
    request,
    metadata || {},
    this.methodDescriptorDeleteBusinessRelation);
  }

}

