/**
 * @fileoverview gRPC-Web generated client stub for business.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.32.1
// source: business/v1/claim_request.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as business_v1_claim_request_pb from '../../business/v1/claim_request_pb'; // proto import: "business/v1/claim_request.proto"


export class ClaimRequestServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateClaimRequest = new grpcWeb.MethodDescriptor(
    '/business.v1.ClaimRequestService/CreateClaimRequest',
    grpcWeb.MethodType.UNARY,
    business_v1_claim_request_pb.CreateClaimRequestRequest,
    business_v1_claim_request_pb.CreateClaimRequestResponse,
    (request: business_v1_claim_request_pb.CreateClaimRequestRequest) => {
      return request.serializeBinary();
    },
    business_v1_claim_request_pb.CreateClaimRequestResponse.deserializeBinary
  );

  createClaimRequest(
    request: business_v1_claim_request_pb.CreateClaimRequestRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_claim_request_pb.CreateClaimRequestResponse>;

  createClaimRequest(
    request: business_v1_claim_request_pb.CreateClaimRequestRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_claim_request_pb.CreateClaimRequestResponse) => void): grpcWeb.ClientReadableStream<business_v1_claim_request_pb.CreateClaimRequestResponse>;

  createClaimRequest(
    request: business_v1_claim_request_pb.CreateClaimRequestRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_claim_request_pb.CreateClaimRequestResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.ClaimRequestService/CreateClaimRequest',
        request,
        metadata || {},
        this.methodDescriptorCreateClaimRequest,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.ClaimRequestService/CreateClaimRequest',
    request,
    metadata || {},
    this.methodDescriptorCreateClaimRequest);
  }

  methodDescriptorGetClaimRequest = new grpcWeb.MethodDescriptor(
    '/business.v1.ClaimRequestService/GetClaimRequest',
    grpcWeb.MethodType.UNARY,
    business_v1_claim_request_pb.GetClaimRequestRequest,
    business_v1_claim_request_pb.GetClaimRequestResponse,
    (request: business_v1_claim_request_pb.GetClaimRequestRequest) => {
      return request.serializeBinary();
    },
    business_v1_claim_request_pb.GetClaimRequestResponse.deserializeBinary
  );

  getClaimRequest(
    request: business_v1_claim_request_pb.GetClaimRequestRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_claim_request_pb.GetClaimRequestResponse>;

  getClaimRequest(
    request: business_v1_claim_request_pb.GetClaimRequestRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_claim_request_pb.GetClaimRequestResponse) => void): grpcWeb.ClientReadableStream<business_v1_claim_request_pb.GetClaimRequestResponse>;

  getClaimRequest(
    request: business_v1_claim_request_pb.GetClaimRequestRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_claim_request_pb.GetClaimRequestResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.ClaimRequestService/GetClaimRequest',
        request,
        metadata || {},
        this.methodDescriptorGetClaimRequest,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.ClaimRequestService/GetClaimRequest',
    request,
    metadata || {},
    this.methodDescriptorGetClaimRequest);
  }

  methodDescriptorListClaimRequests = new grpcWeb.MethodDescriptor(
    '/business.v1.ClaimRequestService/ListClaimRequests',
    grpcWeb.MethodType.UNARY,
    business_v1_claim_request_pb.ListClaimRequestsRequest,
    business_v1_claim_request_pb.ListClaimRequestsResponse,
    (request: business_v1_claim_request_pb.ListClaimRequestsRequest) => {
      return request.serializeBinary();
    },
    business_v1_claim_request_pb.ListClaimRequestsResponse.deserializeBinary
  );

  listClaimRequests(
    request: business_v1_claim_request_pb.ListClaimRequestsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_claim_request_pb.ListClaimRequestsResponse>;

  listClaimRequests(
    request: business_v1_claim_request_pb.ListClaimRequestsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_claim_request_pb.ListClaimRequestsResponse) => void): grpcWeb.ClientReadableStream<business_v1_claim_request_pb.ListClaimRequestsResponse>;

  listClaimRequests(
    request: business_v1_claim_request_pb.ListClaimRequestsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_claim_request_pb.ListClaimRequestsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.ClaimRequestService/ListClaimRequests',
        request,
        metadata || {},
        this.methodDescriptorListClaimRequests,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.ClaimRequestService/ListClaimRequests',
    request,
    metadata || {},
    this.methodDescriptorListClaimRequests);
  }

  methodDescriptorApproveClaimRequest = new grpcWeb.MethodDescriptor(
    '/business.v1.ClaimRequestService/ApproveClaimRequest',
    grpcWeb.MethodType.UNARY,
    business_v1_claim_request_pb.ApproveClaimRequestRequest,
    business_v1_claim_request_pb.ApproveClaimRequestResponse,
    (request: business_v1_claim_request_pb.ApproveClaimRequestRequest) => {
      return request.serializeBinary();
    },
    business_v1_claim_request_pb.ApproveClaimRequestResponse.deserializeBinary
  );

  approveClaimRequest(
    request: business_v1_claim_request_pb.ApproveClaimRequestRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_claim_request_pb.ApproveClaimRequestResponse>;

  approveClaimRequest(
    request: business_v1_claim_request_pb.ApproveClaimRequestRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_claim_request_pb.ApproveClaimRequestResponse) => void): grpcWeb.ClientReadableStream<business_v1_claim_request_pb.ApproveClaimRequestResponse>;

  approveClaimRequest(
    request: business_v1_claim_request_pb.ApproveClaimRequestRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_claim_request_pb.ApproveClaimRequestResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.ClaimRequestService/ApproveClaimRequest',
        request,
        metadata || {},
        this.methodDescriptorApproveClaimRequest,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.ClaimRequestService/ApproveClaimRequest',
    request,
    metadata || {},
    this.methodDescriptorApproveClaimRequest);
  }

  methodDescriptorRejectClaimRequest = new grpcWeb.MethodDescriptor(
    '/business.v1.ClaimRequestService/RejectClaimRequest',
    grpcWeb.MethodType.UNARY,
    business_v1_claim_request_pb.RejectClaimRequestRequest,
    business_v1_claim_request_pb.RejectClaimRequestResponse,
    (request: business_v1_claim_request_pb.RejectClaimRequestRequest) => {
      return request.serializeBinary();
    },
    business_v1_claim_request_pb.RejectClaimRequestResponse.deserializeBinary
  );

  rejectClaimRequest(
    request: business_v1_claim_request_pb.RejectClaimRequestRequest,
    metadata?: grpcWeb.Metadata | null): Promise<business_v1_claim_request_pb.RejectClaimRequestResponse>;

  rejectClaimRequest(
    request: business_v1_claim_request_pb.RejectClaimRequestRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: business_v1_claim_request_pb.RejectClaimRequestResponse) => void): grpcWeb.ClientReadableStream<business_v1_claim_request_pb.RejectClaimRequestResponse>;

  rejectClaimRequest(
    request: business_v1_claim_request_pb.RejectClaimRequestRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: business_v1_claim_request_pb.RejectClaimRequestResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/business.v1.ClaimRequestService/RejectClaimRequest',
        request,
        metadata || {},
        this.methodDescriptorRejectClaimRequest,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/business.v1.ClaimRequestService/RejectClaimRequest',
    request,
    metadata || {},
    this.methodDescriptorRejectClaimRequest);
  }

}

