/**
 * @fileoverview gRPC-Web generated client stub for plans_features.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.32.1
// source: feature.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.plans_features = {};
proto.plans_features.v1 = require('./feature_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.plans_features.v1.FeatureManagementClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.plans_features.v1.FeatureManagementPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.plans_features.v1.CreateFeatureRequest,
 *   !proto.plans_features.v1.FeatureResponse>}
 */
const methodDescriptor_FeatureManagement_CreateFeature = new grpc.web.MethodDescriptor(
  '/plans_features.v1.FeatureManagement/CreateFeature',
  grpc.web.MethodType.UNARY,
  proto.plans_features.v1.CreateFeatureRequest,
  proto.plans_features.v1.FeatureResponse,
  /**
   * @param {!proto.plans_features.v1.CreateFeatureRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.plans_features.v1.FeatureResponse.deserializeBinary
);


/**
 * @param {!proto.plans_features.v1.CreateFeatureRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.plans_features.v1.FeatureResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.plans_features.v1.FeatureResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.plans_features.v1.FeatureManagementClient.prototype.createFeature =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/plans_features.v1.FeatureManagement/CreateFeature',
      request,
      metadata || {},
      methodDescriptor_FeatureManagement_CreateFeature,
      callback);
};


/**
 * @param {!proto.plans_features.v1.CreateFeatureRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.plans_features.v1.FeatureResponse>}
 *     Promise that resolves to the response
 */
proto.plans_features.v1.FeatureManagementPromiseClient.prototype.createFeature =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/plans_features.v1.FeatureManagement/CreateFeature',
      request,
      metadata || {},
      methodDescriptor_FeatureManagement_CreateFeature);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.plans_features.v1.GetFeatureRequest,
 *   !proto.plans_features.v1.FeatureResponse>}
 */
const methodDescriptor_FeatureManagement_GetFeature = new grpc.web.MethodDescriptor(
  '/plans_features.v1.FeatureManagement/GetFeature',
  grpc.web.MethodType.UNARY,
  proto.plans_features.v1.GetFeatureRequest,
  proto.plans_features.v1.FeatureResponse,
  /**
   * @param {!proto.plans_features.v1.GetFeatureRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.plans_features.v1.FeatureResponse.deserializeBinary
);


/**
 * @param {!proto.plans_features.v1.GetFeatureRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.plans_features.v1.FeatureResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.plans_features.v1.FeatureResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.plans_features.v1.FeatureManagementClient.prototype.getFeature =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/plans_features.v1.FeatureManagement/GetFeature',
      request,
      metadata || {},
      methodDescriptor_FeatureManagement_GetFeature,
      callback);
};


/**
 * @param {!proto.plans_features.v1.GetFeatureRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.plans_features.v1.FeatureResponse>}
 *     Promise that resolves to the response
 */
proto.plans_features.v1.FeatureManagementPromiseClient.prototype.getFeature =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/plans_features.v1.FeatureManagement/GetFeature',
      request,
      metadata || {},
      methodDescriptor_FeatureManagement_GetFeature);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.plans_features.v1.ListFeaturesRequest,
 *   !proto.plans_features.v1.ListFeaturesResponse>}
 */
const methodDescriptor_FeatureManagement_ListFeatures = new grpc.web.MethodDescriptor(
  '/plans_features.v1.FeatureManagement/ListFeatures',
  grpc.web.MethodType.UNARY,
  proto.plans_features.v1.ListFeaturesRequest,
  proto.plans_features.v1.ListFeaturesResponse,
  /**
   * @param {!proto.plans_features.v1.ListFeaturesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.plans_features.v1.ListFeaturesResponse.deserializeBinary
);


/**
 * @param {!proto.plans_features.v1.ListFeaturesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.plans_features.v1.ListFeaturesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.plans_features.v1.ListFeaturesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.plans_features.v1.FeatureManagementClient.prototype.listFeatures =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/plans_features.v1.FeatureManagement/ListFeatures',
      request,
      metadata || {},
      methodDescriptor_FeatureManagement_ListFeatures,
      callback);
};


/**
 * @param {!proto.plans_features.v1.ListFeaturesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.plans_features.v1.ListFeaturesResponse>}
 *     Promise that resolves to the response
 */
proto.plans_features.v1.FeatureManagementPromiseClient.prototype.listFeatures =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/plans_features.v1.FeatureManagement/ListFeatures',
      request,
      metadata || {},
      methodDescriptor_FeatureManagement_ListFeatures);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.plans_features.v1.UpdateFeatureRequest,
 *   !proto.plans_features.v1.FeatureResponse>}
 */
const methodDescriptor_FeatureManagement_UpdateFeature = new grpc.web.MethodDescriptor(
  '/plans_features.v1.FeatureManagement/UpdateFeature',
  grpc.web.MethodType.UNARY,
  proto.plans_features.v1.UpdateFeatureRequest,
  proto.plans_features.v1.FeatureResponse,
  /**
   * @param {!proto.plans_features.v1.UpdateFeatureRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.plans_features.v1.FeatureResponse.deserializeBinary
);


/**
 * @param {!proto.plans_features.v1.UpdateFeatureRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.plans_features.v1.FeatureResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.plans_features.v1.FeatureResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.plans_features.v1.FeatureManagementClient.prototype.updateFeature =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/plans_features.v1.FeatureManagement/UpdateFeature',
      request,
      metadata || {},
      methodDescriptor_FeatureManagement_UpdateFeature,
      callback);
};


/**
 * @param {!proto.plans_features.v1.UpdateFeatureRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.plans_features.v1.FeatureResponse>}
 *     Promise that resolves to the response
 */
proto.plans_features.v1.FeatureManagementPromiseClient.prototype.updateFeature =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/plans_features.v1.FeatureManagement/UpdateFeature',
      request,
      metadata || {},
      methodDescriptor_FeatureManagement_UpdateFeature);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.plans_features.v1.DeleteFeatureRequest,
 *   !proto.plans_features.v1.DeleteFeatureResponse>}
 */
const methodDescriptor_FeatureManagement_DeleteFeature = new grpc.web.MethodDescriptor(
  '/plans_features.v1.FeatureManagement/DeleteFeature',
  grpc.web.MethodType.UNARY,
  proto.plans_features.v1.DeleteFeatureRequest,
  proto.plans_features.v1.DeleteFeatureResponse,
  /**
   * @param {!proto.plans_features.v1.DeleteFeatureRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.plans_features.v1.DeleteFeatureResponse.deserializeBinary
);


/**
 * @param {!proto.plans_features.v1.DeleteFeatureRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.plans_features.v1.DeleteFeatureResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.plans_features.v1.DeleteFeatureResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.plans_features.v1.FeatureManagementClient.prototype.deleteFeature =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/plans_features.v1.FeatureManagement/DeleteFeature',
      request,
      metadata || {},
      methodDescriptor_FeatureManagement_DeleteFeature,
      callback);
};


/**
 * @param {!proto.plans_features.v1.DeleteFeatureRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.plans_features.v1.DeleteFeatureResponse>}
 *     Promise that resolves to the response
 */
proto.plans_features.v1.FeatureManagementPromiseClient.prototype.deleteFeature =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/plans_features.v1.FeatureManagement/DeleteFeature',
      request,
      metadata || {},
      methodDescriptor_FeatureManagement_DeleteFeature);
};


module.exports = proto.plans_features.v1;

